export const AI_TOPICS = [

  //app integration n8n
  "1Shot API",
  "2Chat",
  "Action Network",
  "ActiveCampaign",
  "Acuity Scheduling",
  "Adalo",
  "AI Agent",
  "AI Agent Tool",
  "AI Scraper",
  "AI/ML API",
  "AIR",
  "Airtable",
  "Airtop",
  "AMQP Sender",
  "Anthropic",
  "Anthropic Chat Model",
  "Apaleo Official",
  "Apex",
  "Apify",
  "APITemplate.io",
  "Asana",
  "Authentica",
  "Auto-fixing Output Parser",
  "Autobound",
  "Autocalls",
  "Automizy",
  "Autopilot",
  "AWS Bedrock Chat Model",
  "AWS Certificate Manager",
  "AWS Cognito",
  "AWS Comprehend",
  "AWS DynamoDB",
  "AWS ELB",
  "AWS IAM",
  "AWS Lambda",
  "AWS Rekognition",
  "AWS S3",
  "AWS SES",
  "AWS SNS",
  "AWS SQS",
  "AWS Textract",
  "AWS Transcribe",
  "Azure Cosmos DB",
  "Azure OpenAI Chat Model",
  "Azure Storage",
  "BambooHR",
  "Bannerbear",
  "Baserow",
  "Basic LLM Chain",
  "Bedrijfsdata",
  "Beeminder",
  "Beyond Presence",
  "Bitbucket",
  "Bitly",
  "Bitwarden",
  "Blotato",
  "Blue",
  "Box",
  "Brandfetch",
  "Brave Search",
  "BrightData",
  "Browserflow for Linkedin",
  "Bubble",
  "Businessmap",
  "Cal.com",
  "Calculator",
  "Calendly",
  "Call n8n Workflow Tool",
  "Character Text Splitter",
  "Chargebee",
  "Chat Data",
  "Chat Memory Manager",
  "CircleCI",
  "Clearbit",
  "ClickUp",
  "Clockify",
  "CloudConvert",
  "Cloudflare",
  "Cloudinary",
  "Cockpit",
  "Coda",
  "Code Tool",
  "Cohere Chat Model",
  "Cohere Model",
  "CoinGecko",
  "CometAPI",
  "Contentful",
  "Contextual Compression Retriever",
  "ConvertKit",
  "Copacake",
  "Copper",
  "Cortex",
  "CraftMyPdf",
  "CrateDB",
  "Cronlytic",
  "crowd.dev",
  "Customer Datastore",
  "Customer Messenger",
  "Customer.io",
  "Dalil AI",
  "Dart",
  "DebugHelper",
  "Decodo",
  "DeepL",
  "DeepSeek Chat Model",
  "Default Data Loader",
  "Demio",
  "DeutschlandGPT",
  "DHL",
  "DigitalOcean Gradient",
  "Discourse",
  "Disqus",
  "Documentero",
  "DocuWriter.ai",
  "Drift",
  "Dropbox",
  "Dropcontact",
  "Elastic Security",
  "Elasticsearch",
  "ElevenLabs",
  "Embeddings AWS Bedrock",
  "Embeddings Azure OpenAI",
  "Embeddings Cohere",
  "Embeddings Google Gemini",
  "Embeddings Google PaLM",
  "Embeddings Google Vertex",
  "Embeddings Hugging Face Inference",
  "Embeddings Mistral Cloud",
  "Embeddings Ollama",
  "Embeddings OpenAI",
  "Enginemailer",
  "ERPNext",
  "Evaluation",
  "Eventbrite",
  "Explorium API",
  "Extract AI",
  "Facebook",
  "Facebook Graph API",
  "Facebook Lead Ads",
  "Featherless",
  "Figma (Beta)",
  "FileMaker",
  "Fillout",
  "Firecrawl",
  "Fireflies",
  "Flow",
  "FluentC Translate",
  "Form.io",
  "Formstack",
  "Freshdesk",
  "Freshservice",
  "Freshworks CRM",
  "FullEnrich",
  "Gainium",
  "GetResponse",
  "Ghost",
  "GitHub",
  "GitHub Document Loader",
  "GitLab",
  "Globalping",
  "Gong",
  "Google Ads",
  "Google Analytics",
  "Google BigQuery",
  "Google Books",
  "Google Business Profile",
  "Google Chat",
  "Google Cloud Firestore",
  "Google Cloud Natural Language",
  "Google Cloud Realtime Database",
  "Google Cloud Storage",
  "Google Contacts",
  "Google Docs",
  "Google Drive",
  "Google Gemini",
  "Google Gemini Chat Model",
  "Google PaLM Chat Model",
  "Google PaLM Language Model",
  "Google Perspective",
  "Google Slides",
  "Google Sheets",
  "Google Tasks",
  "Google Translate",
  "Google Vertex Chat Model",
  "Google Workspace Admin",
  "Gotify",
  "gotoHuman",
  "GoToWebinar",
  "Grafana",
  "GraphQL",
  "Grist",
  "Groq Chat Model",
  "Gumroad",
  "Hacker News",
  "HaloPSA",
  "Handelsregister.ai",
  "Harvest",
  "Help Scout",
  "HighLevel",
  "Home Assistant",
  "HTML/CSS to Image",
  "Hubbi",
  "HubSpot",
  "Hugging Face Inference Model",
  "Humantic AI",
  "Hunter",
  "Information Extractor",
  "Inoreader",
  "Instantly",
  "Intercom",
  "Invoice Ninja",
  "Item List Output Parser",
  "Iterable",
  "Jenkins",
  "JigsawStack",
  "Jina AI",
  "Jira",
  "Jira Software",
  "JoAi",
  "JoggAI",
  "JotForm",
  "JWT",
  "Kafka",
  "Keap",
  "Kitemaker",
  "KlickTipp",
  "KoBoToolbox",
  "KrispCall",
  "LangChain Code",
  "Langfuse",
  "Ldap",
  "LEDGERS",
  "Lemlist",
  "Line",
  "Linear",
  "LingvaNex",
  "LinkedIn",
  "Lnk.Bio",
  "LoneScale",
  "Magento 2",
  "Magnetite",
  "Mailcheck",
  "Mailchimp",
  "MailerLite",
  "Mailgun",
  "Mailjet",
  "Mailtrap",
  "Mallabe Images",
  "Mallabe Barcodes",
  "Mandrill",
  "Marketstack",
  "Matrix",
  "Mattermost",
  "Mautic",
  "MCP Client Tool",
  "MCP Server",
  "Medium",
  "Memara",
  "MessageBird",
  "Metabase",
  "Microsoft Dynamics CRM",
  "Microsoft Entra ID",
  "Microsoft Excel 365",
  "Microsoft Graph Security",
  "Microsoft Outlook",
  "Microsoft OneDrive",
  "Microsoft SharePoint",
  "Microsoft SQL",
  "Microsoft Teams",
  "Microsoft To Do",
  "Milvus Vector Store",
  "Mindee",
  "MISP",
  "Mistral AI",
  "Mistral Cloud Chat Model",
  "Mocean",
  "Model Selector",
  "Monday.com",
  "MongoDB",
  "MongoDB Atlas Vector Store",
  "MongoDB Chat Memory",
  "Monica CRM",
  "Motorhead",
  "MQTT",
  "MSG91",
  "MultiQuery Retriever",
  "NASA",
  "Netgsm",
  "Netlify",
  "Netscaler ADC",
  "Nextcloud",
  "NocoDB",
  "Npm",
  "Nuelink",
  "Octagon",
  "Octave",
  "Odoo",
  "Okta",
  "Ollama Chat Model",
  "Ollama Model",
  "Omnara",
  "One Simple API",
  "Onfleet",
  "OpenAI",
  "OpenAI Chat Model",
  "OpenRouter Chat Model",
  "OpenThesaurus",
  "OpenWeatherMap",
  "Orbit",
  "Orq Deployment",
  "Orshot",
  "Oura",
  "Outgrow",
  "Outscraper",
  "Oxylabs AI Studio",
  "Paddle",
  "PagerDuty",
  "Parallel",
  "Parseur",
  "Payfunnels",
  "PayPal",
  "PDF Generator API",
  "PDF Vector",
  "PDF.co Api",
  "PDF4ME",
  "PDFMonkey",
  "Pdforge",
  "Peekalink",
  "Perplexity",
  "Phantombuster",
  "Philips Hue",
  "Pipedrive",
  "Plivo",
  "PostBin",
  "Postgres",
  "Postgres Chat Memory",
  "Postgres PGVector Store",
  "PostHog",
  "Postiz",
  "Postmark",
  "Prisma AIRS",
  "ProfitWell",
  "PromptLayer Run Agent",
  "ProspectPro",
  "Pushbullet",
  "Pushcut",
  "Pushinator",
  "Pushover",
  "Qdrant",
  "Qdrant Vector Store",
  "QuestDB",
  "QuickBooks Online",
  "QuickChart",
  "RabbitMQ",
  "raia",
  "Raindrop",
  "Recursive Character Text Splitter",
  "Reddit",
  "Redis",
  "Redis Chat Memory",
  "Referral Factory",
  "Reportei",
  "Reranker Cohere",
  "RocketChat",
  "RogerRoger",
  "Rundeck",
  "S3",
  "Salesforce",
  "Salesmate",
  "Scrape Creators",
  "Scrapegrap",

  // Additional core tech stacks to cover Cloud, Backend, Frontend, Mobile, DBs, DevOps, ML, and Specialized fields
  // Cloud Platforms & Infrastructure
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Oracle Cloud",
  "Alibaba Cloud",
  "IBM Cloud",
  "DigitalOcean",
  "Vultr",
  "Linode",
  "Heroku",
  "Vercel",
  "Netlify",
  "VMware",
  "OpenStack",
  "Proxmox",
  "Azure Functions",
  "Google Cloud Functions",
  "Cloudflare Workers",

  // Backend languages & frameworks
  "Node.js",
  "Express.js",
  "NestJS",
  "Koa",
  "Fastify",
  "Django",
  "Flask",
  "FastAPI",
  "Spring",
  "Quarkus",
  "ASP.NET Core",
  "Laravel",
  "Symfony",
  "Ruby on Rails",
  "Gin (Go)",
  "Echo (Go)",
  "Actix (Rust)",
  "Rocket (Rust)",

  // APIs & messaging
  "REST API",
  "GraphQL",
  "gRPC",
  "WebSockets",
  "Apache Kafka",
  "RabbitMQ",

  // Frontend core & frameworks
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "SolidJS",
  "Preact",
  "Tailwind CSS",
  "Bootstrap",
  "Material-UI",
  "SASS/SCSS",
  "Styled-components",
  "Emotion",
  "Next.js",
  "Nuxt.js",
  "SvelteKit",
  "Gatsby",
  "Astro",
  "Remix",
  "Vite",
  "Webpack",
  "Rollup",
  "Parcel",

  // Mobile
  "Swift",
  "Objective-C",
  "SwiftUI",
  "Kotlin",
  "Java (Android)",
  "Jetpack Compose",
  "React Native",
  "Flutter",
  ".NET MAUI",
  "Ionic",
  "Kotlin Multiplatform",

  // --- Mobile App Development (native & cross-platform) ---
  // IDEs / Tooling
  "Xcode",
  "Android Studio",

  // Device-side storage & DBs
  "SQLite",
  "Realm",
  "Core Data",
  "Room",
  "MMKV",

  // Push & notifications
  "Firebase Cloud Messaging (FCM)",
  "OneSignal",
  "Apple Push Notification Service (APNS)",

  // Analytics & crash reporting
  "Firebase Analytics",
  "Crashlytics",
  "Sentry",
  "Datadog",
  "Mixpanel",
  "Instabug",

  // CI/CD & testing
  "Fastlane",
  "Bitrise",
  "Codemagic",
  "GitHub Actions",
  "Jenkins",

  // Distribution & beta testing
  "Apple App Store",
  "Google Play Store",
  "TestFlight",
  "Google Play Console",
  "Firebase App Distribution",

  // Dependency managers
  "CocoaPods",
  "Swift Package Manager",
  "Gradle",
  "npm",
  "Yarn",

  // Databases
  "PostgreSQL",
  "MySQL",
  "Microsoft SQL Server",
  "Oracle Database",
  "SQLite",
  "MariaDB",
  "MongoDB",
  "Cassandra",
  "HBase",
  "Neo4j",
  "Algolia",
  "Meilisearch",
  "InfluxDB",
  "TimescaleDB",
  "Pinecone",
  "Milvus",
  "Weaviate",
  "Chroma DB",
  "Qdrant",

  // DevOps & Operations
  "Docker",
  "Kubernetes",
  "Podman",
  "Docker Swarm",
  "Jenkins",
  "GitLab CI/CD",
  "GitHub Actions",
  "CircleCI",
  "Travis CI",
  "TeamCity",
  "Terraform",
  "Ansible",
  "Pulumi",
  "Chef",
  "Puppet",
  "CloudFormation",
  "Prometheus",
  "Grafana",
  "Datadog",
  "New Relic",
  "Splunk",
  "ELK Stack",
  "Git",

  // Big Data & AI/ML
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Keras",
  "Hugging Face",
  "OpenCV",
  "Apache Spark",
  "Apache Flink",
  "Apache Hadoop",
  "Dask",
  "Snowflake",
  "Databricks",
  "Kubeflow",
  "MLflow",
  "Weights & Biases",
  "Jupyter",
  "Apache Airflow",
  "Tableau",
  "Power BI",

  // Specialized fields
  "WordPress",
  "Strapi",
  "Sanity.io",
  "Shopify",
  "WooCommerce",
  "BigCommerce",
  "Ethereum",
  "Solidity",
  "Solana",
  "Web3.js",
  "Ethers.js",
  "Hardhat",
  "Unity",
  "Unreal Engine",
  "Godot",
  // --- Game Development (engines, tools, graphics, audio, physics) ---
  // Engines & frameworks
  "GameMaker Studio",
  "CryEngine",
  "Cocos2d-x",
  "Cocos2d",
  "RPG Maker",

  // Graphics & content creation
  "Blender",
  "Autodesk Maya",
  "Autodesk 3ds Max",
  "ZBrush",
  "Aseprite",
  "Spine",
  "Krita",
  "Substance 3D Painter",
  "Substance Designer",
  "Quixel Mixer",

  // Low-level graphics APIs
  "DirectX",
  "OpenGL",
  "Vulkan",
  "Metal",

  // Audio & physics
  "FMOD",
  "Wwise",
  "FL Studio",
  "Ableton Live",
  "Reaper",
  "Logic Pro X",
  "Box2D",
  "PhysX",
  "Havok",
  "Bullet Physics",

  // Networking & multiplayer backends
  "Unreal Networking Engine",
  "Netcode for GameObjects",
  "Photon Engine",
  "Nakama",
  "AWS GameLift",
  "Azure PlayFab",
  "Google Cloud Game Servers",

  // Distribution & platforms
  "Steam",
  "Epic Games Store",
  "GOG",
  "itch.io",
  "WebGL",
  "MQTT",
  "Arduino",
  "Raspberry Pi",
  "AWS IoT Core",
  "Azure IoT Hub",
  "Wireshark",
  "Metasploit",
  "Nmap",
  "Burp Suite",
  "OWASP ZAP",
  "Bubble",
  "Webflow",
  "Retool",
  "Zapier",
  "Make",
  "n8n",
  // Hugging Face specific items
  "Hugging Face Hub",
  "Transformers (Hugging Face)",
  "Datasets (Hugging Face)",
  "Tokenizers (Hugging Face)",
  "Spaces (Hugging Face)",
  "Inference Endpoints (Hugging Face)",
  "AutoTrain (Hugging Face)",
  "Gradio",
  "Streamlit",

  // Docker Hub specific items
  "Docker Desktop",
  "Docker Engine",
  "Docker Hub Registry",
  "Docker Automated Builds",
  "Docker Scout",
  "OCI Distribution Specification",

  // GitHub related / infra
  "Git LFS",
  "Vitess",
  "GitHub Actions",

  // Languages / runtimes / frameworks referenced by platforms
  "Python",
  "Rust",
  "JAX",
  // Core languages commonly used across backend and infra
  "Go",
  "Java",
  "C#",
  "PHP",
  "Scala",
  "Elixir",
  "Julia",
  // Popular & general-purpose languages (added from checklist)
  "JavaScript",
  "TypeScript",
  "C++",
  "C",
  "Ruby",
  "Swift",
  "Kotlin",

  // Systems & performance languages
  "Zig",
  "Assembly",

  // Data science / AI / ML languages
  "R",

  // Functional / ML-influenced languages
  "Haskell",
  "Lisp",
  "Clojure",
  "F#",
  "OCaml",

  // Domain-specific / scripting / tooling languages
  "Lua",
  "Groovy",
  "MATLAB",
  "HCL",

  // Historical / influential languages
  "Fortran",
  "COBOL",
  "Pascal",
  "Ada",
  "Perl",
  "Smalltalk",

  // GPUs / ML infra
  "NVIDIA A100",
  "NVIDIA H100",
  "CUDA",
  "Triton Inference Server",
  "TorchServe",

  // MLOps / tooling
  "Weights & Biases",
  "MLflow",

  // Backend frameworks and microservices helpers
  "Starlette",

  // BaaS / Realtime
  "Firebase",
  "Supabase",
  // Additional platform/tooling items suggested
  // Hugging Face ecosystem extensions
  "Diffusers (Hugging Face)",
  "Accelerate (Hugging Face)",
  "Optimum (Hugging Face)",

  // Docker extras
  "docker-compose",
  "Docker CLI",
  "Dockerfile",

  // GitHub extras
  "GitHub Codespaces",
  "GitHub Packages",
  "GitHub Copilot",
  "GitHub Marketplace",
  "Codespaces devcontainer",

  // GitOps / Kubernetes ecosystem
  "Helm",
  "Kustomize",
  "Argo CD",
  "Flux",
  "OpenTelemetry",
  "Istio",
  "Linkerd",
  "Consul",

  // Ingress / proxies
  "Nginx",
  "Traefik",

  // Observability / quality
  "Sentry",
  "SonarQube",

  // Data movement / ELT
  "Airbyte",
  "Fivetran",

  // Auth / identity / secrets
  "Keycloak",
  "Auth0",
  "Vault (HashiCorp Vault)",

  // Additional databases
  "Couchbase",
  "ArangoDB",

  // Distributed compute / ML infra
  "Ray",
  // Cloud managed services & serverless
  "AWS EKS",
  "Google GKE",
  "Azure AKS",
  "AWS ECS",
  "Google Cloud Run",
  "Serverless Framework",

  // Model serving & inference frameworks
  "BentoML",
  "Seldon Core",
  "KFServing",
  "ONNX",
  "ONNX Runtime",
  "TensorRT",

  // Additional ML platforms / managed services
  "AWS SageMaker",
  "Azure Machine Learning",
  "Google Vertex AI",

  // GraphQL / realtime backend
  "Hasura",
  // Container registries
  "Amazon ECR",
  "Google Artifact Registry",
  "Azure Container Registry (ACR)",

  // Security / dependency tooling
  "Dependabot",
  // --- Cybersecurity (Blue Team / Defensive Security) ---
  // Firewalls & NGFWs
  "Palo Alto Networks",
  "Fortinet",
  "FortiGate",
  "Cisco ASA",
  "Cisco Firepower",
  "Check Point",
  "pfSense",
  "OPNsense",

  // IDS / IPS
  "Snort",
  "Suricata",
  "Zeek (Bro)",

  // Endpoint & EDR/XDR
  "CrowdStrike Falcon",
  "SentinelOne",
  "Carbon Black",
  "Microsoft Defender for Endpoint",

  // SIEM / Log Management (some already present)
  "IBM QRadar",
  "LogRhythm",

  // WAF / Email / CASB
  "ModSecurity",
  "Cloudflare WAF",
  "Akamai Kona Site Defender",
  "Imperva WAF",
  "F5 BIG-IP ASM",
  "Proofpoint",
  "Mimecast",
  "Barracuda",
  "Netskope",
  "McAfee Skyhigh",
  "Microsoft Defender for Cloud Apps",

  // --- Cybersecurity (Red Team / Offensive Security) ---
  "Nessus",
  "OpenVAS",
  "Qualys",
  "Nexpose",
  "Nikto",
  "SQLMap",
  "John the Ripper",
  "Hashcat",
  "Cobalt Strike",
  "Brute Ratel",
  "Covenant",

  // --- Analysis, Forensics & Threat Intel ---
  "tcpdump",
  "Volatility",
  "Autopsy",
  "The Sleuth Kit",
  "EnCase",
  "Cellebrite UFED",
  "Cuckoo Sandbox",
  "ANY.RUN",
  "Ghidra",
  "IDA Pro",
  "x64dbg",
  "ThreatQuotient",
  "Anomali",

  // --- DevSecOps / App Security ---
  "Veracode",
  "Checkmarx",
  "Snyk",
  "Black Duck",
  "Aqua Security",
  "Twistlock",
  "Sysdig",
  "Falco",

  // --- Networking & Internet (Protocols, Hardware & Services) ---
  // Core protocols
  "IPv4",
  "IPv6",
  "ICMP",
  "TCP",
  "UDP",
  "BGP",
  "OSPF",
  "EIGRP",
  "IS-IS",
  "HTTP/1.1",
  "HTTP/2",
  "HTTP/3",
  "DNS",
  "SMTP",
  "POP3",
  "IMAP",
  "FTP",
  "SFTP",
  "SSH",
  "TLS",
  "IPsec",

  // Hardware vendors & appliances
  "Cisco",
  "Juniper Networks",
  "Arista Networks",
  "Hewlett Packard Enterprise (HPE)",
  "Mikrotik",
  "F5 Networks",
  "Citrix",
  "Cisco Meraki",
  "Ubiquiti",
  "Aruba (HPE)",
  "Ruckus",

  // DNS / CDN / Load balancing
  "BIND",
  "PowerDNS",
  "Knot DNS",
  "Fastly",
  "AWS CloudFront",
  "HAProxy",

  // SDN & virtualization
  "OpenFlow",
  "VMware NSX",
  "Cisco ACI",
  "VeloCloud",
  "Viptela",
  "SD-WAN",
  "VXLAN",
  "VPC",
  "VNet",
  "Google VPC",

  // Monitoring & automation
  "SNMP",
  "NetFlow",
  "sFlow",
  "Zabbix",
  "Nagios",
  "PRTG Network Monitor",
  "Netmiko",
  "NAPALM",
];

export const AI_TOPICS_STRING = AI_TOPICS.join(", ");
